# Generated by Django 4.0.6 on 2022-07-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=250, verbose_name='Покупатель')),
                ('number', models.CharField(max_length=250, unique=True, verbose_name='Номер чека')),
                ('store', models.CharField(max_length=250, verbose_name='Магазин')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Время выдачи чека')),
                ('check_amount', models.IntegerField(verbose_name='Сумма чека')),
            ],
        ),
        migrations.CreateModel(
            name='PositionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('position_amount', models.IntegerField(verbose_name='Сумма')),
                ('parent_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='check.check', verbose_name='Чек')),
            ],
        ),
    ]
